# Generated by Django 5.1.6 on 2025-03-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "승인 대기"),
                    ("approved", "승인 완료"),
                    ("rejected", "승인 거절"),
                    ("attended", "참석"),
                    ("absence", "불참"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
