# Generated by Django 5.1.6 on 2025-03-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelter",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
