# Generated by Django 5.1.7 on 2025-03-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0003_shelter_contact_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="business_registration_email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="business_registration_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("서울", "서울"),
                    ("부산", "부산"),
                    ("대구", "대구"),
                    ("인천", "인천"),
                    ("광주", "광주"),
                    ("대전", "대전"),
                    ("울산", "울산"),
                    ("세종", "세종"),
                    ("경기", "경기"),
                    ("강원", "강원"),
                    ("충북", "충북"),
                    ("충남", "충남"),
                    ("전북", "전북"),
                    ("전남", "전남"),
                    ("경북", "경북"),
                    ("경남", "경남"),
                    ("제주", "제주"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="shelter_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("corporation", "Corporation"),
                    ("individual", "Individual"),
                    ("non_profit", "Non-Profit"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shelterimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
