# Generated by Django 5.1.6 on 2025-03-20 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0003_shelter_contact_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShelterImage",
        ),
    ]
