# Generated by Django 5.1.7 on 2025-03-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0004_alter_shelter_address_and_more"),
        ("shelters", "0004_delete_shelterimage"),
    ]

    operations = []
