# Generated by Django 5.1.6 on 2025-03-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitment",
            name="description",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cleaning", "견사청소"),
                    ("grooming", "미용"),
                    ("bathing", "목욕"),
                    ("walking", "산책"),
                    ("feeding", "밥주기"),
                    ("other", "기타"),
                ],
                default="",
                max_length=50,
                null=True,
            ),
        ),
    ]
