# Generated by Django 5.1.6 on 2025-03-20 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0003_alter_recruitment_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitmentImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image_url", models.URLField()),
                (
                    "recruitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recruitments.recruitment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
