# Generated by Django 5.1.7 on 2025-03-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0004_recruitmentimage"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="recruitmentimage",
            table="recruitment_images",
        ),
    ]
