# Generated by Django 5.1.6 on 2025-03-10 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("histories", "0001_initial"),
        ("shelters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="shelter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="histories",
                to="shelters.shelter",
            ),
        ),
    ]
